In [112]:
import numpy as np 
import cv2 
import matplotlib.pyplot as plt
import PIL.Image as Image
import gym
import random

from ready_trader_go import BaseAutoTrader, Instrument, Lifespan, MAXIMUM_ASK, MINIMUM_BID, Side

from gym import Env
from gym.spaces import Box
import time

font = cv2.FONT_HERSHEY_COMPLEX_SMALL 

In [82]:
class TradingEnv(Env):
    def __init__(self):
        super(TradingEnv, self).__init__()

        self.observation_space = Box(low=0, high=2400, shape=(1,))

        # Define an action space ranging from 0 to 4
        self.action_space = Box(low=-1, high=1, shape=(2,))

        self.profit = 0
        self.etf_position = 0
        self.fut_position = 0

        self.start_state = np.zeros(2400)
        
    def reset(self):
        self.profit = 0
        self.etf_position = 0
        self.fut_position = 0
        return self.start_state

    def step(self, action):
        done = False

        if action[1] > 0:
            side = Side.BUY
        else:
            side = Side.SELL
        
        volume = round(abs(a[1])*100)
        
        if action[0] > 0:
            instrument = Instrument.ETF

        else:
            instrument = Instrument.FUTURE

            

In [83]:
env = OrderBook()
obs = env.reset()
obs

array([0., 0., 0., ..., 0., 0., 0.])

In [136]:
a = env.action_space.sample()
a

array([-0.13766612,  0.05964515], dtype=float32)

In [137]:
round(abs(a[1])*100)

6

In [81]:
Box(low=-1, high=1, shape=(2,))

Box(-1.0, 1.0, (2,), float32)

In [35]:
list(np.array([-1]))

[-1]

C:\venvs\rtg\lib\site-packages\gym\spaces\box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float16
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


Box(-1.0, 1.0, (1,), float16)

In [26]:
observation_shape = (2402)


In [27]:
observation_space

Box(0.0, 10000.0, (2402,), float16)

In [25]:
np.ones(observation_shape) * 5

array([5., 5., 5., ..., 5., 5., 5.])

In [113]:
Instrument.ETF

<Instrument.ETF: 1>